### ISSUE TITLE
Error: `tokio::spawn failed (is a tokio runtime running this future?)"))`

### ISSUE THREAD

**Issue by felipellrocha** [leshow/twilio#2]
Hi,

I'm getting this error when trying to use this library:
```
thread 'main' panicked at 'Could not send text: (+1xxx, +1xxx, "Hello World"): NetworkErr(Error(User(Execute), "tokio::spawn failed (is a tokio runtime running this future?)"))', src/libcore/result.rs:1165:5
```

Here is the code breaking:
```
let client = Twilio::new(&self.account_sid, &self.token)
      .expect("Could not init client");
    let (_, resp) = client
      .send_msg(&self.number, &to, &message)
      .run()
      .compat()
      .await
      .expect(&format!("Could not send text: ({:}, {:}, {:})", &self.number, &to, &message));
```

**Comment by leshow** [comment]
Yes, it looks like it's failing because you haven't spawned the future in a runtime. The version currently on `crates.io` is for tokio 0.1, have a look at the readme for that [version](https://github.com/leshow/twilio-async/tree/eb1b5c26634ac41087e1a6310d36964d6efa9431)


notably, you have to make a new `Core` and run each future inside it: 
```
core.run(twilio
    .send_msg("from", "to", "body")
    .media("http://i0.kym-cdn.com/photos/images/newsfeed/000/377/946/0b9.jpg")
    .run())?;
```

I haven't used tokio-compat so I don't know what the equivalent is, but my guess is you need to `tokio::spawn`. 

If you can, try pointing to the version on master. **It's updated to tokio 0.2 and using async/await.** I just haven't released it on crates yet

**Comment by leshow** [comment]
I'm going to publish a new version. Please re-open if you have any other comments
